[package]
name = "cmus-notify"
version = "0.1.0"
authors = ["AB <ultradesu@hexor.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "3"
dbus = "0.8.2"
chrono = "0.4"
